# Generated by Django 5.2.7 on 2025-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do aluno', max_length=100)),
                ('cpf', models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, unique=True)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo')),
                ('data_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
            ],
        ),
    ]
