# Generated by Django 5.2.7 on 2025-11-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Plano de Mensalidade',
                'verbose_name_plural': 'Planos de Mensalidade',
                'ordering': ['valor'],
            },
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades', to='core.planomensalidade'),
        ),
    ]
