# Generated by Django 5.2.7 on 2025-11-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planomensalidade_mensalidade_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.planomensalidade', verbose_name='Plano de Mensalidade'),
        ),
    ]
